### ISSUE TITLE
Frontend-Backend-Verbindung [Backend]

### ISSUE THREAD

**Issue by Philip-Bachl** [TeamVentureDive/Parallax#110]

**Comment by Rahulditi** [comment]
can you assign it to me?

**Comment by Philip-Bachl** [comment]
who are you?

**Comment by Tripolt** [comment]
Just create a pull request when you finished our project. Thanks

**Comment by Tripolt** [comment]
> can you assign it to me?

Just create a pull request when you finished our project. Thanks
