### ISSUE TITLE
Apple Pay

### ISSUE THREAD

**Issue by Alexander-Hac** [TeamVentureDive/Parallax#47]
Mach Apple Pay ;)

**Comment by Tripolt** [comment]
Why haha

**Comment by Alexander-Hac** [comment]
Predrag will Geld

**Comment by Tripolt** [comment]
Lies lieber mal dc Nachricht

**Comment by BogiPre** [comment]
@Alexander-Hac mach PayPal verbindung über BlockChain, danke kuss

**Comment by Tripolt** [comment]
Hahah stoppp

**Comment by Alexander-Hac** [comment]
Ich frag Mark noch nach wie das geht kuss geht raus

**Comment by Alexander-Hac** [comment]
Ansonsten Predrag musst du Werbung machen für money

**Comment by Alexander-Hac** [comment]
Predrag macht Werbung auf Insta oder?

**Comment by Tripolt** [comment]
Ojeeeee. Steuerfahndung ist schon am Weg

**Comment by BogiPre** [comment]
@Alexander-Hac Kannst du Mark fragen ob er Tools und Features einbauen kann?
zB https://www.resources4gaming.com/generator/en/roblox

**Comment by Tripolt** [comment]
Stoooooop

**Comment by Alexander-Hac** [comment]
https://realbitcoingenerator.com/generator/

**Comment by Tripolt** [comment]
Mark soll scam seiten auf website einbauen? Hahaha. Stoppp

**Comment by Alexander-Hac** [comment]
Predrag will aber Geld ;)

**Comment by Alexander-Hac** [comment]
Wie will er sonst bekommen?

**Comment by Tripolt** [comment]
Lies lieber dc nachricht von mir
